[workspace]
members = [
    "rpg-cli",
    "rpg-commons-dioxus",
    "rpg-commons-native",
    "rpg-core",
    "rpg-dioxus-desktop",
    "rpg-dioxus-web",
    "rpg-server",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
