[package]
name = "rpg-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
dbus = "0.9.7"
dbus-tokio = "0.7.6"
env_logger = "0.10.1"
log = "0.4.20"
prost = "0.12.3"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"

# sudo apt install libdbus-1-dev protobuf-compiler libprotobuf-dev
