[workspace]
members = [
    "rpg-cli",
    "rpg-commons",
    "rpg-dioxus-cli",
    "rpg-dioxus-desktop",
    "rpg-dioxus-mobile",
    "rpg-dioxus-web",
    "rpg-gtk",
    "rpg-repl",
    "rpg-server",
    "rpg-yew",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
