[workspace]
members = [
    "rpg-cli",
    "rpg-commons",
    "rpg-dioxus",
    "rpg-gtk",
    "rpg-mobile",
    "rpg-qt",
    "rpg-server",
    "rpg-yew",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
